Enable keyboard shortcut to mute from any tab (no perms)
BashVideo/google-meet-push-to-talk pull request #10
Opened 2020-05-27 23:20 UTC by nedarb

Allow a global (throughout all browser windows) mute/unmute toggle keyboard shortcut

Note: this does not add any new extension permissions, unlike PR #7 did

2020-05-29 16:39 UTC, tpott commented on src/background.js
> +  console.assert(port.name == "meet");
nit: add a message to this assertion, something like `"Unexpected content script connection %s", port.name)`

2020-05-29 16:39 UTC, tpott commented on src/background.js
> +  if (command === "toggle-meeting-mute" && ports.size > 0) {
nit: I'd invert this and return early. I.e. `if (command !== 'toggle' || ports.size === 0) { return; }` (but using newlines)

2020-05-29 16:41 UTC, tpott commented
https://media.giphy.com/media/48FhEMYGWji8/giphy.gif

2020-06-02 15:26 UTC, nedarb commented
Thanks @tpott - I tweaked those things you mentioned

2020-06-02 16:11 UTC, tpott commented
Thanks! Can you add @stopdropandrew as a reviewer? I'm not associated with BashVideo, so I can't accept PRs

2020-06-19 18:54 UTC, nedarb commented
@stopdropandrew can I get code review of this?

2020-07-12 23:46 UTC, at-avacron commented
I'm not a programmer, but background functionality is a big deal for me. I have my hotkey set to **shift**. There's a Chrome-only web app that I need to run at the same time as Meet, whose mute/unmute hotkey can only be **shift**, and whose tab has to be in focus to receive that command. If GMPTT could address a background Meet tab, I could use one key to simultaneously unmute GMPTT and mute the other app.

2020-07-25 03:47 UTC, stopdropandrew requested changes
Sorry about the delay on this, been busy. Mostly looks great, I had to change the mac hotkey to make it work. I really wish we could track keydown/up and make this PTT but a toggle is better than nothing. Great work! I won't let it sit long this time 😅

2020-07-25 03:47 UTC, stopdropandrew commented on src/manifest.json
> +        "mac": "Ctrl+Space"
Can you change this to `"MacCtrl+Space"` ? On Mac cmd-space opens spotlight search.

2020-07-25 03:47 UTC, stopdropandrew commented on package.json
> +    "@types/chrome": "^0.0.114",
Is this needed? No typescript here

2020-07-25 03:47 UTC, stopdropandrew commented on src/ptt.js
> +    const onButton = document.querySelector(micButtonSelector(MIC_ON));
Can you change this to work with the new language support?

2020-08-26 20:19 UTC, nedarb commented
@stopdropandrew I think I addressed your comments in the latest commits, if you have time to look

2021-01-05 11:52 UTC, karlhorky commented
Ah this would be cool! @stopdropandrew do you think this could get merged?

2021-03-20 17:35 UTC, merged